project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!renv/"
    - "!certificate*"
  resources:
    - "files/"
    - "slides/"
  preview:
    port: 4321
    browser: true
    watch-inputs: false
execute:
  freeze: auto   # Re-render only when source changes
  echo: true #Include the source code in output
  message: false # don't show messages
  warning: false #don't include warnings in the output
  output: true #include the results of executing the code
  cache: false # don't cache code junks by default
description-meta: "Website for the 2024 SISMID Module on Infectious Diseases, Immunology and Within-Host Models."
editor: 
  markdown: 
    wrap: sentence
engine: knitr
website:
  title: "SISMID 2025"
  site-url: "https://andreashandel.github.io/SISMID2025/"
  description: "Website for the 2025 SISMID Module on Infectious Diseases, Immunology and Within-Host Models."
  favicon: /files/sismid-logo-horizontal-2024.jpg 
  cookie-consent: false    
  search: true
  navbar:
    left:
      - text: "Syllabus"
        file: Course_Syllabus.qmd
      - text: "Schedule"
        file: Course_Schedule.qmd
      - text: "Communication"
        file: Course_Communication.qmd
      - text: "Resources"
        file: Course_Resources.qmd
      - text: "Project"
        file: Course_Project.qmd
format:
  html:
    code-fold: false
    #embed-resources: true	
    #self-contained: true
    theme: 
      light: [lumen]
      dark: [slate]
    toc: false